# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "048364cef3f567f10c505beec421258b"
application_url = "https://chatbot.kiz.app"
embedded = true
name = "chatbot"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products"

[app_proxy]
url = "https://chatbot-backend.kiz.app"
subpath = "ai-chatbot"
prefix = "apps"

[product.metafields.app.demo_info]
type = "single_line_text_field"
name = "Demo Source Info"
description = "Tracks products created by the Shopify app template for development"

  [product.metafields.app.demo_info.access]
  admin = "merchant_read_write"

[metaobjects.app.example]
name = "Example"
description = "An example metaobject definition created by this template"

  [metaobjects.app.example.access]
  admin = "merchant_read_write"

[metaobjects.app.example.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.example.fields.description]
name = "Description"
type = "multi_line_text_field"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]
  include_fields = ["admin_graphql_api_id", "name"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/privacy"
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]

[auth]
redirect_urls = [ "https://chatbot.kiz.app/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
