import { useLoaderData, useActionData, useSubmit, useNavigation, useRevalidator } from "react-router";
import { useState, useEffect } from "react";
import { authenticate } from "../shopify.server";
import { boundary } from "@shopify/shopify-app-react-router/server";
import db from "../db.server";

const ALLOWED_TONES = ["standard", "enthusiastic"];
const MAX_INSTRUCTIONS_LENGTH = 2000;

export const loader = async ({ request }) => {
    const { session } = await authenticate.admin(request);

    const personaSettings = await db.aipersonasettings.upsert({
        where: { sessionId: session.id },
        create: { sessionId: session.id },
        update: {},
    });

    return {
        ...personaSettings
    };
};

export const action = async ({ request }) => {
    const { session } = await authenticate.admin(request);
    const formData = await request.formData();
    const actionType = formData.get("_action");

    const customInstructions = (formData.get("customInstructions"))?.trim() || null;
    const tone = formData.get("tone");

    if (customInstructions && customInstructions.length > MAX_INSTRUCTIONS_LENGTH) {
        return { error: `Custom instructions must be ${MAX_INSTRUCTIONS_LENGTH} characters or fewer.` };
    }

    if (!ALLOWED_TONES.includes(tone)) {
        return { error: "Invalid tone selected." };
    }

    await db.aipersonasettings.upsert({
        where: { sessionId: session.id },
        create: { sessionId: session.id, customInstructions, tone },
        update: { customInstructions, tone },
    });

    return { success: true };
};

export default function AiPersona() {
    const settings = useLoaderData();
    const actionData = useActionData();
    const navigation = useNavigation();
    const submit = useSubmit();

    // Only the persona fields belong in editable form state — sync status
    // comes straight from the loader so it stays fresh across revalidations.
    const { customInstructions, tone } = settings;
    const [initialFormState, setInitialFormState] = useState({ customInstructions, tone });
    const [formState, setFormState] = useState({ customInstructions, tone });

    const isSaving = navigation.state === "submitting";
    const isDirty = JSON.stringify(formState) !== JSON.stringify(initialFormState);

    function handleSave(e) {
        e.preventDefault();
        submit(
            {
                customInstructions: formState.customInstructions || "",
                tone: formState.tone,
            },
            { method: "post" }
        );
    }

    function handleReset() {
        setFormState(initialFormState);
    }

    useEffect(() => {
        const saveBar = document.getElementById("ai-persona-save-bar");
        if (!saveBar) return;
        isDirty ? saveBar.show() : saveBar.hide();
    }, [isDirty]);

    useEffect(() => {
        if (actionData?.success) {
            window.shopify.toast.show("Settings saved", { duration: 3000 });
            setInitialFormState(formState);
        }
        if (actionData?.error) {
            window.shopify.toast.show(actionData.error, { isError: true, duration: 3000 });
        }
    }, [actionData]);

    return (
        <form onSubmit={handleSave}>
            <ui-save-bar id="ai-persona-save-bar">
                <button variant="primary" disabled={isSaving} loading={isSaving ? "" : false} type="submit"></button>
                <button disabled={isSaving} onClick={handleReset} type="button"></button>
            </ui-save-bar>

            <s-section heading="AI Persona & Custom Instructions">
                <s-text-area
                    autocomplete="off"
                    details={`Write clear rules or store context to direct the AI's responses. Optional — leave blank to use the default persona.`}
                    label="Custom System Instructions"
                    placeholder="e.g., You are a friendly customer support agent for [Store Name]. Help customers track orders, check sizing, and answer store policy questions. Always maintain a helpful tone and do not discuss competitor brands."
                    rows={5}
                    maxLength={MAX_INSTRUCTIONS_LENGTH}
                    value={formState.customInstructions || ""}
                    onInput={(e) => setFormState({ ...formState, customInstructions: e.currentTarget.value })}
                ></s-text-area>
                <s-select
                    label="AI Tone of Voice"
                    details="Controls the emotional delivery and style of responses generated by the AI."
                    value={formState.tone}
                    onChange={(e) => setFormState({ ...formState, tone: e.currentTarget.value })}
                >
                    <s-option value="standard">Standard & Professional</s-option>
                    <s-option value="enthusiastic">Enthusiastic & Friendly</s-option>
                </s-select>
            </s-section>
        </form >
    );
}

export const headers = (headersArgs) => boundary.headers(headersArgs);